# Generated by Django 2.2.1 on 2019-05-27 16:23

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190524_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=100)),
                ('place', models.CharField(default='Place name', max_length=100)),
                ('info', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=32)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=32)),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=events.models.infrastructures_image_path)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.Infrastructure')),
            ],
        ),
    ]
