# Generated by Django 2.2.1 on 2019-05-27 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_infrastructure_infrastructureimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='infrastructures', to=settings.AUTH_USER_MODEL),
        ),
    ]
